== Pact: Where does it come from

https://github.com/pact-foundation[pact-foundation-github]
the ideas from consumer driven contracts
break up your integration tests into unit tests

== Pact: Concepts


=== Pact: Example

=== Pact: Provider State

=== Pact: Provider Side Changes break Client

* forget IgnoreUnknowns on Java DTO and add additional fields on the Provider.

=== Pact: Matchers

What elements can be matched

https://docs.pact.io/documentation/matching.html
https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit
https://github.com/DiUS/pact-jvm/wiki/Matching#matcher-path-expressions

=== Pact: Findings

Matchers: 85 vs. 85.0
Consumer passing arguments for state changes works only on pact-jvm?


[NOTE.speaker]
--
equals is used to compare numbers
matching more complex string cases seem to be fiddly.
maybe lack of knowledge/experience with the tool?
Limitation of the jvm implementation?
--

=== Pact: Contact
https://gitter.im/realestate-com-au/pact[Gitter]

=== https://github.com/pact-foundation/pact_broker[Pact Broker]

- https://pact.dius.com.au/[free hosted pact brokers]

verification results are published back to the broker
- What is it
- https://github.com/pact-foundation/pact_broker[pact-broker on github]
- https://github.com/pact-foundation/pact_broker/wiki/Overview
- https://github.com/pact-foundation/pact_broker/wiki/Using-tags
- https://github.com/pact-foundation/pact_broker/wiki/How-to-ensure-backwards-compatibility-by-tagging-pacts

[NOTE.speaker]
--
pact test should be unit tests https://github.com/DiUS/pact-jvm/issues/640#issuecomment-367525621[Source]
--


=== Pact: What changed between versions

v1

v2

Auf 3:
 provider state -> provider states
 message queues

=== Pact: Where to use it
- If you control code for the consumer and the provider
- public apis are not suited, better of with Swagger documentation

=== Pact: What can not be ensured with this approach
- Firewall rules and network connectivity

=== Pact: What benefits do you see?
- You know your clients
- You get people from the consumer talking to the producer people
- Easier tracing which fields are use and by whom