version: '3'

services:

  jenkins:
    image: jenkins/jenkins:2.178-slim
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins/var:/var/jenkins_home

  postgres:
    image: postgres:11.3-alpine
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pact_broker:
    image: pactfoundation/pact-broker:edge   #https://hub.docker.com/r/dius/pact-broker/
    ports:
      - "80:9292"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PASSENGER_DISABLE_SECURITY_UPDATE_CHECK: "true"
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: "http https"
      PACT_BROKER_WEBHOOK_HOST_WHITELIST: "jenkins"
