version: '3'

services:
  postgres:
    image: postgres:11.3-alpine
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/var:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pact_broker:
    image: pactfoundation/pact-broker:2.52.2-1
    ports:
      - "80:9292"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PASSENGER_DISABLE_SECURITY_UPDATE_CHECK: "true"
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: "http https"
      PACT_BROKER_WEBHOOK_HOST_WHITELIST: "jenkins"
      PACT_BROKER_LOG_LEVEL: INFO

  jenkins:
    image: jenkins/jenkins:2.232-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins/var:/var/jenkins_home
